const Lang = {
    MSG_SUCCESS: 'Success:',
    MSG_ERROR: 'Error: ',
    HELP_MESSAGE: '--h: help message',
    BUILDIN: {
        CMD_NAME: 'input folder name',
        CMD_DESCRIPTION: 'input description for command',
        EXSITED: 'has exsited',
        NOT_EXSITED: 'not exsited',
        IS_CREATD_TMPL_FOLDER: 'is need create template folder',
        IS_RUN_ANNY_PATH: 'is only run command in project root path',
        CMD_CREATE_SUCCESS: `Command file created success`,
        NAME_NO_WHITESPACE: "file name don't have whitespace",
        NAME_NO_SPECIAL_CHARACTER: 'file name only include "-" or "_" special character',
        NAME_LOWERCASE: 'file name must use lowercase',
        ADD_CMD_CONFIG: 'add to cmd config',
        ADD_CMD_CONFIG_SUCCESS: 'add to cmd config success',
        ADD_CMD_EXTENSIONS: 'add to extensions',
        ADD_CMD_EXTENSIONS_SUCCESS: 'add to extensions success',
        ADD_CMD_PACKAGE: 'add to package.json',
        ADD_CMD_PACKAGE_SUCCESS: 'add to package.json success',
        NO_COMMAND: 'no this command by named',
        MEAN_SUCH: 'you mean is above such:',
        COMMAND_LENGTH_TOO_LONG: 'command length too long',
        NO_THIS_FOLDER: 'not found folder by this name',
        DELETE_COMMAND_TIPS: 'will delete command files',
        DELETE_COMMAND_SUCCESS: 'delete command files success',
        DELETE_COMMAND_FLOW_SUCCESS: 'delete command flow has done',
        CLI_HAS_READY: 'cli has ready and will execute command',
        CLI_VOLIDATING_CMD: 'cli volidating command',
        CLI_VOLIDATE_CMD_SUCCESS: 'cli volidate command successed',
        OBSCURE_SOURCE_ROOT: 'input root directory of source code ',
        OBSCURE_OUTPUT_ROOT: 'input root directory source code obscured ',
        OBSCURING_CODE: 'obscuring source code',
        OBSCURE_CODE_DONE: 'obscure source code done',
        OBSCURE_FLOW_DONE: 'obscure source code flow done'
    },
    EXTENSION: {
        CHOICE_PROJECT_TYPE: 'choice project type',
        CHOICE_PROJECT_STACK: 'choice project stack',
        SUPORT_LATER: 'not suport at now',
        PROJECT_NAME: 'input project name',
        PROJECT_WILL_CREATE: 'project files will be create',
        PROJECT_CREATE_SUCCESS: 'project files created success',
        PROJECT_INSTALL_TIPS: "project will install packages,dot't close window",
        PROJECT_CREATE_FLOW_DONE: 'project flow of create has done',
        CREATE_PKG_DONE: 'create application package.json done',
        CREATE_WEBPACK_DONE: 'create application webpack done',
        CREATE_PROJECT_DONE: 'create application files done',
        PROJECT_FOLDER_PATH: 'project folder at',
        TMPL_NOT_EXSITED: 'template file not exsited',

    }
};

module.exports = { Lang };